import { readFile, writeFile } from "node:fs/promises";
import { createLocalSchema } from "./local-schema.ts";

type Column = {
  table_name: string;
  column_name: string;
  udt_name: string;
  is_nullable: string;
  has_default: boolean;
  is_generated: string;
};
type Relationship = {
  table_name: string;
  foreign_key_name: string;
  columns: string[];
  referenced_relation: string;
  referenced_columns: string[];
  is_one_to_one: boolean;
};
type Rpc = {
  name: string;
  arg_names: string[];
  arg_types: string[];
  defaults: number;
  return_type: string;
  returns_set: boolean;
};

// This generator deliberately supports the SQL types used by this contract.
// Unknown types fail generation instead of silently weakening the generated types.
function tsType(pgType: string): string {
  if (pgType.startsWith("_")) return `${tsType(pgType.slice(1))}[]`;
  switch (pgType) {
    case "uuid": case "text": case "timestamptz": return "string";
    case "int2": case "int4": case "int8": return "number";
    case "bool": return "boolean";
    case "jsonb": return "Json";
    default: throw new Error(`Unsupported database type: ${pgType}`);
  }
}

const { db, schemaHash } = await createLocalSchema();
try {
  const { rows: columns } = await db.query<Column>(`
    select table_name, column_name, udt_name, is_nullable,
      column_default is not null as has_default, is_generated
    from information_schema.columns
    where table_schema = 'public'
    order by table_name, ordinal_position
  `);
  const tables = [...new Set(columns.map((column) => column.table_name))];
  const { rows: relationships } = await db.query<Relationship>(`
    select c.conrelid::regclass::text as table_name, c.conname as foreign_key_name,
      array(select a.attname from unnest(c.conkey) with ordinality k(num, pos)
        join pg_attribute a on a.attrelid=c.conrelid and a.attnum=k.num order by k.pos) as columns,
      c.confrelid::regclass::text as referenced_relation,
      array(select a.attname from unnest(c.confkey) with ordinality k(num, pos)
        join pg_attribute a on a.attrelid=c.confrelid and a.attnum=k.num order by k.pos) as referenced_columns,
      exists(select 1 from pg_constraint u where u.conrelid=c.conrelid
        and u.contype in ('p','u') and u.conkey @> c.conkey and u.conkey <@ c.conkey) as is_one_to_one
    from pg_constraint c
    join pg_class t on t.oid=c.conrelid
    join pg_namespace n on n.oid=t.relnamespace
    join pg_class target on target.oid=c.confrelid
    join pg_namespace tn on tn.oid=target.relnamespace
    where c.contype='f' and n.nspname='public' and tn.nspname='public'
    order by table_name, foreign_key_name
  `);
  const { rows: functions } = await db.query<Rpc>(`
    select p.proname as name, p.proargnames as arg_names,
      array(select t.typname from unnest(p.proargtypes) with ordinality a(oid, pos)
        join pg_type t on t.oid=a.oid order by a.pos) as arg_types,
      p.pronargdefaults as defaults, r.typname as return_type, p.proretset as returns_set
    from pg_proc p join pg_namespace n on n.oid=p.pronamespace
      join pg_type r on r.oid=p.prorettype
    where n.nspname='public' order by p.proname
  `);
  const lines = [
    "// Generated by npm run db:types from the supplied SQL in temporary PGlite.",
    "// Do not edit by hand. This is a local contract snapshot, not remote introspection.",
    `// SQL SHA-256 (LF-normalized): ${schemaHash}`,
    "// SQL CHECK constraints remain runtime constraints; JSON is not domain-validated here.",
    "export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];",
    "", "export type Database = {", "  public: {", "    Tables: {",
  ];
  for (const table of tables) {
    lines.push(`      ${table}: {`);
    for (const operation of ["Row", "Insert", "Update"] as const) {
      lines.push(`        ${operation}: {`);
      for (const column of columns.filter((value) => value.table_name === table)) {
        const nullable = column.is_nullable === "YES";
        const generated = column.is_generated !== "NEVER";
        const optional = operation !== "Row" && (operation === "Update" || nullable || column.has_default || generated);
        const type = generated && operation !== "Row" ? "never" : tsType(column.udt_name) + (nullable ? " | null" : "");
        lines.push(`          ${column.column_name}${optional ? "?" : ""}: ${type};`);
      }
      lines.push("        };");
    }
    lines.push("        Relationships: [");
    for (const relationship of relationships.filter((value) => value.table_name === table)) {
      lines.push("          {",
        `            foreignKeyName: ${JSON.stringify(relationship.foreign_key_name)};`,
        `            columns: ${JSON.stringify(relationship.columns)};`,
        `            isOneToOne: ${relationship.is_one_to_one};`,
        `            referencedRelation: ${JSON.stringify(relationship.referenced_relation)};`,
        `            referencedColumns: ${JSON.stringify(relationship.referenced_columns)};`,
        "          },");
    }
    lines.push("        ];", "      };");
  }
  lines.push("    };", "    Views: { [_ in never]: never };", "    Functions: {");
  for (const rpc of functions) {
    lines.push(`      ${rpc.name}: {`, "        Args: {");
    rpc.arg_names.forEach((name, index) => {
      const optional = index >= rpc.arg_names.length - rpc.defaults;
      // PostgreSQL RPC arguments accept SQL NULL unless the function validates otherwise.
      lines.push(`          ${name}${optional ? "?" : ""}: ${tsType(rpc.arg_types[index]!)} | null;`);
    });
    const returnType = tables.includes(rpc.return_type)
      ? `Database["public"]["Tables"]["${rpc.return_type}"]["Row"]`
      : tsType(rpc.return_type);
    lines.push("        };", `        Returns: ${returnType}${rpc.returns_set ? "[]" : ""};`, "      };");
  }
  lines.push("    };", "    Enums: { [_ in never]: never };", "    CompositeTypes: { [_ in never]: never };", "  };", "};", "",
    `export const publicTableNames = ${JSON.stringify(tables, null, 2)} as const;`, "");
  const output = lines.join("\n");
  const destination = new URL("../../types/database.ts", import.meta.url);
  if (process.argv.includes("--check")) {
    if (await readFile(destination, "utf8") !== output) {
      throw new Error("Database types differ from the SQL contract. Run npm run db:types.");
    }
    console.log(`Database types match all ${tables.length} tables and ${functions.length} RPCs.`);
  } else {
    await writeFile(destination, output);
    console.log(`Generated database types for ${tables.length} tables and ${functions.length} RPCs.`);
  }
} finally {
  await db.close();
}
