// Generated by npm run db:types from the supplied SQL in temporary PGlite.
// Do not edit by hand. This is a local contract snapshot, not remote introspection.
// SQL SHA-256 (LF-normalized): 855c68ca7b97426dc6b04f40b52c6566115cabd40e0a371516240e9dae17ccf7
// SQL CHECK constraints remain runtime constraints; JSON is not domain-validated here.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      ai_explanations: {
        Row: {
          id: string;
          analysis_id: string;
          repository_id: string;
          explanation_version: string;
          status: string;
          provider: string;
          model: string | null;
          summary: string | null;
          highest_risk_path: Json | null;
          reviewer_question: string | null;
          input_tokens: number | null;
          output_tokens: number | null;
          error_code: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          analysis_id: string;
          repository_id: string;
          explanation_version?: string;
          status?: string;
          provider?: string;
          model?: string | null;
          summary?: string | null;
          highest_risk_path?: Json | null;
          reviewer_question?: string | null;
          input_tokens?: number | null;
          output_tokens?: number | null;
          error_code?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          analysis_id?: string;
          repository_id?: string;
          explanation_version?: string;
          status?: string;
          provider?: string;
          model?: string | null;
          summary?: string | null;
          highest_risk_path?: Json | null;
          reviewer_question?: string | null;
          input_tokens?: number | null;
          output_tokens?: number | null;
          error_code?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "ai_explanations_analysis_id_repository_id_fkey";
            columns: ["analysis_id","repository_id"];
            isOneToOne: false;
            referencedRelation: "analyses";
            referencedColumns: ["id","repository_id"];
          },
        ];
      };
      analyses: {
        Row: {
          id: string;
          repository_id: string;
          pull_request_id: string;
          head_sha: string;
          base_sha: string;
          comparison_base_sha: string | null;
          analyzer_version: string;
          configuration_version: number;
          settings_snapshot: Json;
          head_snapshot_id: string | null;
          base_snapshot_id: string | null;
          status: string;
          stage: string;
          progress: number;
          publishing_status: string;
          impact_score: number | null;
          changed_count: number;
          direct_count: number;
          indirect_count: number;
          reachable_count: number;
          entry_point_count: number;
          test_count: number;
          test_gap_count: number;
          files_total: number;
          files_parsed: number;
          files_failed: number;
          imports_resolved: number;
          imports_unresolved: number;
          traversal_truncated: boolean;
          warnings: Json;
          previous_analysis_id: string | null;
          delta: Json;
          error_code: string | null;
          error_message: string | null;
          started_at: string | null;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          repository_id: string;
          pull_request_id: string;
          head_sha: string;
          base_sha: string;
          comparison_base_sha?: string | null;
          analyzer_version?: string;
          configuration_version?: number;
          settings_snapshot?: Json;
          head_snapshot_id?: string | null;
          base_snapshot_id?: string | null;
          status?: string;
          stage?: string;
          progress?: number;
          publishing_status?: string;
          impact_score?: number | null;
          changed_count?: number;
          direct_count?: number;
          indirect_count?: number;
          reachable_count?: number;
          entry_point_count?: number;
          test_count?: number;
          test_gap_count?: number;
          files_total?: number;
          files_parsed?: number;
          files_failed?: number;
          imports_resolved?: number;
          imports_unresolved?: number;
          traversal_truncated?: boolean;
          warnings?: Json;
          previous_analysis_id?: string | null;
          delta?: Json;
          error_code?: string | null;
          error_message?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          repository_id?: string;
          pull_request_id?: string;
          head_sha?: string;
          base_sha?: string;
          comparison_base_sha?: string | null;
          analyzer_version?: string;
          configuration_version?: number;
          settings_snapshot?: Json;
          head_snapshot_id?: string | null;
          base_snapshot_id?: string | null;
          status?: string;
          stage?: string;
          progress?: number;
          publishing_status?: string;
          impact_score?: number | null;
          changed_count?: number;
          direct_count?: number;
          indirect_count?: number;
          reachable_count?: number;
          entry_point_count?: number;
          test_count?: number;
          test_gap_count?: number;
          files_total?: number;
          files_parsed?: number;
          files_failed?: number;
          imports_resolved?: number;
          imports_unresolved?: number;
          traversal_truncated?: boolean;
          warnings?: Json;
          previous_analysis_id?: string | null;
          delta?: Json;
          error_code?: string | null;
          error_message?: string | null;
          started_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "analyses_base_snapshot_id_repository_id_fkey";
            columns: ["base_snapshot_id","repository_id"];
            isOneToOne: false;
            referencedRelation: "graph_snapshots";
            referencedColumns: ["id","repository_id"];
          },
          {
            foreignKeyName: "analyses_head_snapshot_id_repository_id_fkey";
            columns: ["head_snapshot_id","repository_id"];
            isOneToOne: false;
            referencedRelation: "graph_snapshots";
            referencedColumns: ["id","repository_id"];
          },
          {
            foreignKeyName: "analyses_previous_analysis_id_pull_request_id_repository_i_fkey";
            columns: ["previous_analysis_id","pull_request_id","repository_id"];
            isOneToOne: false;
            referencedRelation: "analyses";
            referencedColumns: ["id","pull_request_id","repository_id"];
          },
          {
            foreignKeyName: "analyses_pull_request_id_repository_id_fkey";
            columns: ["pull_request_id","repository_id"];
            isOneToOne: false;
            referencedRelation: "pull_requests";
            referencedColumns: ["id","repository_id"];
          },
        ];
      };
      analysis_changes: {
        Row: {
          id: string;
          analysis_id: string;
          repository_id: string;
          path: string;
          previous_path: string | null;
          change_type: string;
          additions: number;
          deletions: number;
          is_supported: boolean;
          skip_reason: string | null;
        };
        Insert: {
          id?: string;
          analysis_id: string;
          repository_id: string;
          path: string;
          previous_path?: string | null;
          change_type: string;
          additions?: number;
          deletions?: number;
          is_supported?: boolean;
          skip_reason?: string | null;
        };
        Update: {
          id?: string;
          analysis_id?: string;
          repository_id?: string;
          path?: string;
          previous_path?: string | null;
          change_type?: string;
          additions?: number;
          deletions?: number;
          is_supported?: boolean;
          skip_reason?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "analysis_changes_analysis_id_repository_id_fkey";
            columns: ["analysis_id","repository_id"];
            isOneToOne: false;
            referencedRelation: "analyses";
            referencedColumns: ["id","repository_id"];
          },
        ];
      };
      analysis_nodes: {
        Row: {
          id: string;
          analysis_id: string;
          repository_id: string;
          graph_side: string;
          path: string;
          file_type: string;
          distance: number;
          is_changed: boolean;
          is_entry_point: boolean;
          is_test: boolean;
          is_sensitive: boolean;
          route_path: string | null;
          owners: string[];
          reason: string;
          evidence: Json;
        };
        Insert: {
          id?: string;
          analysis_id: string;
          repository_id: string;
          graph_side?: string;
          path: string;
          file_type: string;
          distance: number;
          is_changed?: boolean;
          is_entry_point?: boolean;
          is_test?: boolean;
          is_sensitive?: boolean;
          route_path?: string | null;
          owners?: string[];
          reason: string;
          evidence?: Json;
        };
        Update: {
          id?: string;
          analysis_id?: string;
          repository_id?: string;
          graph_side?: string;
          path?: string;
          file_type?: string;
          distance?: number;
          is_changed?: boolean;
          is_entry_point?: boolean;
          is_test?: boolean;
          is_sensitive?: boolean;
          route_path?: string | null;
          owners?: string[];
          reason?: string;
          evidence?: Json;
        };
        Relationships: [
          {
            foreignKeyName: "analysis_nodes_analysis_id_repository_id_fkey";
            columns: ["analysis_id","repository_id"];
            isOneToOne: false;
            referencedRelation: "analyses";
            referencedColumns: ["id","repository_id"];
          },
        ];
      };
      analysis_score_factors: {
        Row: {
          id: string;
          analysis_id: string;
          repository_id: string;
          factor_key: string;
          label: string;
          points: number;
          evidence: Json;
        };
        Insert: {
          id?: string;
          analysis_id: string;
          repository_id: string;
          factor_key: string;
          label: string;
          points: number;
          evidence?: Json;
        };
        Update: {
          id?: string;
          analysis_id?: string;
          repository_id?: string;
          factor_key?: string;
          label?: string;
          points?: number;
          evidence?: Json;
        };
        Relationships: [
          {
            foreignKeyName: "analysis_score_factors_analysis_id_repository_id_fkey";
            columns: ["analysis_id","repository_id"];
            isOneToOne: false;
            referencedRelation: "analyses";
            referencedColumns: ["id","repository_id"];
          },
        ];
      };
      analysis_test_associations: {
        Row: {
          id: string;
          analysis_id: string;
          repository_id: string;
          target_node_id: string;
          test_path: string;
          graph_side: string;
          association_type: string;
          evidence: Json;
        };
        Insert: {
          id?: string;
          analysis_id: string;
          repository_id: string;
          target_node_id: string;
          test_path: string;
          graph_side?: string;
          association_type: string;
          evidence?: Json;
        };
        Update: {
          id?: string;
          analysis_id?: string;
          repository_id?: string;
          target_node_id?: string;
          test_path?: string;
          graph_side?: string;
          association_type?: string;
          evidence?: Json;
        };
        Relationships: [
          {
            foreignKeyName: "analysis_test_associations_analysis_id_repository_id_fkey";
            columns: ["analysis_id","repository_id"];
            isOneToOne: false;
            referencedRelation: "analyses";
            referencedColumns: ["id","repository_id"];
          },
          {
            foreignKeyName: "analysis_test_associations_target_node_id_analysis_id_repo_fkey";
            columns: ["target_node_id","analysis_id","repository_id"];
            isOneToOne: false;
            referencedRelation: "analysis_nodes";
            referencedColumns: ["id","analysis_id","repository_id"];
          },
        ];
      };
      dependency_edges: {
        Row: {
          id: string;
          repository_id: string;
          snapshot_id: string;
          from_file_id: string;
          to_file_id: string;
          edge_type: string;
          is_type_only: boolean;
          source_line: number;
          import_specifier: string;
        };
        Insert: {
          id?: string;
          repository_id: string;
          snapshot_id: string;
          from_file_id: string;
          to_file_id: string;
          edge_type?: string;
          is_type_only?: boolean;
          source_line?: number;
          import_specifier: string;
        };
        Update: {
          id?: string;
          repository_id?: string;
          snapshot_id?: string;
          from_file_id?: string;
          to_file_id?: string;
          edge_type?: string;
          is_type_only?: boolean;
          source_line?: number;
          import_specifier?: string;
        };
        Relationships: [
          {
            foreignKeyName: "dependency_edges_from_file_id_snapshot_id_repository_id_fkey";
            columns: ["from_file_id","snapshot_id","repository_id"];
            isOneToOne: false;
            referencedRelation: "source_files";
            referencedColumns: ["id","snapshot_id","repository_id"];
          },
          {
            foreignKeyName: "dependency_edges_snapshot_id_repository_id_fkey";
            columns: ["snapshot_id","repository_id"];
            isOneToOne: false;
            referencedRelation: "graph_snapshots";
            referencedColumns: ["id","repository_id"];
          },
          {
            foreignKeyName: "dependency_edges_to_file_id_snapshot_id_repository_id_fkey";
            columns: ["to_file_id","snapshot_id","repository_id"];
            isOneToOne: false;
            referencedRelation: "source_files";
            referencedColumns: ["id","snapshot_id","repository_id"];
          },
        ];
      };
      faultline_schema_version: {
        Row: {
          version: number;
          description: string;
          installed_at: string;
        };
        Insert: {
          version: number;
          description: string;
          installed_at?: string;
        };
        Update: {
          version?: number;
          description?: string;
          installed_at?: string;
        };
        Relationships: [
        ];
      };
      github_comments: {
        Row: {
          pull_request_id: string;
          repository_id: string;
          github_comment_id: number | null;
          last_analysis_id: string | null;
          last_published_head_sha: string | null;
          body_hash: string | null;
          publish_status: string;
          last_error: string | null;
          published_at: string | null;
          updated_at: string;
        };
        Insert: {
          pull_request_id: string;
          repository_id: string;
          github_comment_id?: number | null;
          last_analysis_id?: string | null;
          last_published_head_sha?: string | null;
          body_hash?: string | null;
          publish_status?: string;
          last_error?: string | null;
          published_at?: string | null;
          updated_at?: string;
        };
        Update: {
          pull_request_id?: string;
          repository_id?: string;
          github_comment_id?: number | null;
          last_analysis_id?: string | null;
          last_published_head_sha?: string | null;
          body_hash?: string | null;
          publish_status?: string;
          last_error?: string | null;
          published_at?: string | null;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "github_comments_last_analysis_id_pull_request_id_repositor_fkey";
            columns: ["last_analysis_id","pull_request_id","repository_id"];
            isOneToOne: false;
            referencedRelation: "analyses";
            referencedColumns: ["id","pull_request_id","repository_id"];
          },
          {
            foreignKeyName: "github_comments_pull_request_id_repository_id_fkey";
            columns: ["pull_request_id","repository_id"];
            isOneToOne: false;
            referencedRelation: "pull_requests";
            referencedColumns: ["id","repository_id"];
          },
        ];
      };
      github_installations: {
        Row: {
          id: string;
          user_id: string;
          github_installation_id: number;
          github_account_id: number;
          account_login: string;
          account_type: string;
          repository_selection: string;
          permissions: Json;
          suspended_at: string | null;
          deleted_at: string | null;
          last_verified_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          github_installation_id: number;
          github_account_id: number;
          account_login: string;
          account_type: string;
          repository_selection?: string;
          permissions?: Json;
          suspended_at?: string | null;
          deleted_at?: string | null;
          last_verified_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          github_installation_id?: number;
          github_account_id?: number;
          account_login?: string;
          account_type?: string;
          repository_selection?: string;
          permissions?: Json;
          suspended_at?: string | null;
          deleted_at?: string | null;
          last_verified_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "github_installations_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      graph_snapshots: {
        Row: {
          id: string;
          repository_id: string;
          commit_sha: string;
          index_version: string;
          status: string;
          files_total: number;
          files_parsed: number;
          files_failed: number;
          files_skipped: number;
          imports_resolved: number;
          imports_unresolved: number;
          warnings: Json;
          started_at: string;
          completed_at: string | null;
        };
        Insert: {
          id?: string;
          repository_id: string;
          commit_sha: string;
          index_version?: string;
          status?: string;
          files_total?: number;
          files_parsed?: number;
          files_failed?: number;
          files_skipped?: number;
          imports_resolved?: number;
          imports_unresolved?: number;
          warnings?: Json;
          started_at?: string;
          completed_at?: string | null;
        };
        Update: {
          id?: string;
          repository_id?: string;
          commit_sha?: string;
          index_version?: string;
          status?: string;
          files_total?: number;
          files_parsed?: number;
          files_failed?: number;
          files_skipped?: number;
          imports_resolved?: number;
          imports_unresolved?: number;
          warnings?: Json;
          started_at?: string;
          completed_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "graph_snapshots_repository_id_fkey";
            columns: ["repository_id"];
            isOneToOne: false;
            referencedRelation: "repositories";
            referencedColumns: ["id"];
          },
        ];
      };
      impact_paths: {
        Row: {
          id: string;
          analysis_id: string;
          repository_id: string;
          target_node_id: string;
          graph_side: string;
          path_type: string;
          path_json: Json;
          path_length: number | null;
          evidence: Json;
        };
        Insert: {
          id?: string;
          analysis_id: string;
          repository_id: string;
          target_node_id: string;
          graph_side?: string;
          path_type?: string;
          path_json: Json;
          path_length?: never;
          evidence?: Json;
        };
        Update: {
          id?: string;
          analysis_id?: string;
          repository_id?: string;
          target_node_id?: string;
          graph_side?: string;
          path_type?: string;
          path_json?: Json;
          path_length?: never;
          evidence?: Json;
        };
        Relationships: [
          {
            foreignKeyName: "impact_paths_analysis_id_repository_id_fkey";
            columns: ["analysis_id","repository_id"];
            isOneToOne: false;
            referencedRelation: "analyses";
            referencedColumns: ["id","repository_id"];
          },
          {
            foreignKeyName: "impact_paths_target_node_id_analysis_id_repository_id_fkey";
            columns: ["target_node_id","analysis_id","repository_id"];
            isOneToOne: false;
            referencedRelation: "analysis_nodes";
            referencedColumns: ["id","analysis_id","repository_id"];
          },
        ];
      };
      jobs: {
        Row: {
          id: string;
          installation_id: string | null;
          repository_id: string | null;
          analysis_id: string | null;
          job_type: string;
          dedupe_key: string;
          payload: Json;
          status: string;
          attempt_count: number;
          max_attempts: number;
          next_attempt_at: string;
          worker_id: string | null;
          lease_token: string | null;
          lease_expires_at: string | null;
          last_error_code: string | null;
          last_error: string | null;
          started_at: string | null;
          finished_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          installation_id?: string | null;
          repository_id?: string | null;
          analysis_id?: string | null;
          job_type: string;
          dedupe_key: string;
          payload?: Json;
          status?: string;
          attempt_count?: number;
          max_attempts?: number;
          next_attempt_at?: string;
          worker_id?: string | null;
          lease_token?: string | null;
          lease_expires_at?: string | null;
          last_error_code?: string | null;
          last_error?: string | null;
          started_at?: string | null;
          finished_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          installation_id?: string | null;
          repository_id?: string | null;
          analysis_id?: string | null;
          job_type?: string;
          dedupe_key?: string;
          payload?: Json;
          status?: string;
          attempt_count?: number;
          max_attempts?: number;
          next_attempt_at?: string;
          worker_id?: string | null;
          lease_token?: string | null;
          lease_expires_at?: string | null;
          last_error_code?: string | null;
          last_error?: string | null;
          started_at?: string | null;
          finished_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "jobs_analysis_id_repository_id_fkey";
            columns: ["analysis_id","repository_id"];
            isOneToOne: false;
            referencedRelation: "analyses";
            referencedColumns: ["id","repository_id"];
          },
          {
            foreignKeyName: "jobs_installation_id_fkey";
            columns: ["installation_id"];
            isOneToOne: false;
            referencedRelation: "github_installations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "jobs_repository_id_fkey";
            columns: ["repository_id"];
            isOneToOne: false;
            referencedRelation: "repositories";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "jobs_repository_id_installation_id_fkey";
            columns: ["repository_id","installation_id"];
            isOneToOne: false;
            referencedRelation: "repositories";
            referencedColumns: ["id","installation_id"];
          },
        ];
      };
      profiles: {
        Row: {
          id: string;
          github_user_id: number | null;
          github_login: string | null;
          avatar_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          github_user_id?: number | null;
          github_login?: string | null;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          github_user_id?: number | null;
          github_login?: string | null;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
        ];
      };
      public_demo_reports: {
        Row: {
          id: string;
          slug: string;
          repository_id: string;
          analysis_id: string;
          title: string;
          report: Json;
          published_at: string;
          revoked_at: string | null;
        };
        Insert: {
          id?: string;
          slug?: string;
          repository_id: string;
          analysis_id: string;
          title: string;
          report: Json;
          published_at?: string;
          revoked_at?: string | null;
        };
        Update: {
          id?: string;
          slug?: string;
          repository_id?: string;
          analysis_id?: string;
          title?: string;
          report?: Json;
          published_at?: string;
          revoked_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "public_demo_reports_analysis_id_repository_id_fkey";
            columns: ["analysis_id","repository_id"];
            isOneToOne: false;
            referencedRelation: "analyses";
            referencedColumns: ["id","repository_id"];
          },
        ];
      };
      pull_requests: {
        Row: {
          id: string;
          repository_id: string;
          github_pr_number: number;
          title: string;
          author_login: string;
          head_sha: string;
          base_sha: string;
          head_ref: string | null;
          base_ref: string | null;
          head_repository_full_name: string | null;
          state: string;
          draft: boolean;
          html_url: string;
          opened_at: string;
          github_updated_at: string | null;
          closed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          repository_id: string;
          github_pr_number: number;
          title: string;
          author_login: string;
          head_sha: string;
          base_sha: string;
          head_ref?: string | null;
          base_ref?: string | null;
          head_repository_full_name?: string | null;
          state?: string;
          draft?: boolean;
          html_url: string;
          opened_at?: string;
          github_updated_at?: string | null;
          closed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          repository_id?: string;
          github_pr_number?: number;
          title?: string;
          author_login?: string;
          head_sha?: string;
          base_sha?: string;
          head_ref?: string | null;
          base_ref?: string | null;
          head_repository_full_name?: string | null;
          state?: string;
          draft?: boolean;
          html_url?: string;
          opened_at?: string;
          github_updated_at?: string | null;
          closed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "pull_requests_repository_id_fkey";
            columns: ["repository_id"];
            isOneToOne: false;
            referencedRelation: "repositories";
            referencedColumns: ["id"];
          },
        ];
      };
      repositories: {
        Row: {
          id: string;
          installation_id: string;
          github_repository_id: number;
          owner: string;
          name: string;
          default_branch: string;
          private: boolean;
          html_url: string | null;
          access_removed_at: string | null;
          index_status: string;
          last_indexed_sha: string | null;
          last_indexed_at: string | null;
          last_error: string | null;
          traversal_depth: number;
          max_source_files: number;
          max_changed_files: number;
          max_file_bytes: number;
          max_total_source_bytes: number;
          sensitive_path_rules: Json;
          configuration_version: number;
          ai_enabled: boolean;
          ai_private_metadata_opt_in: boolean;
          ai_score_threshold: number;
          is_public_demo: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          installation_id: string;
          github_repository_id: number;
          owner: string;
          name: string;
          default_branch?: string;
          private?: boolean;
          html_url?: string | null;
          access_removed_at?: string | null;
          index_status?: string;
          last_indexed_sha?: string | null;
          last_indexed_at?: string | null;
          last_error?: string | null;
          traversal_depth?: number;
          max_source_files?: number;
          max_changed_files?: number;
          max_file_bytes?: number;
          max_total_source_bytes?: number;
          sensitive_path_rules?: Json;
          configuration_version?: number;
          ai_enabled?: boolean;
          ai_private_metadata_opt_in?: boolean;
          ai_score_threshold?: number;
          is_public_demo?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          installation_id?: string;
          github_repository_id?: number;
          owner?: string;
          name?: string;
          default_branch?: string;
          private?: boolean;
          html_url?: string | null;
          access_removed_at?: string | null;
          index_status?: string;
          last_indexed_sha?: string | null;
          last_indexed_at?: string | null;
          last_error?: string | null;
          traversal_depth?: number;
          max_source_files?: number;
          max_changed_files?: number;
          max_file_bytes?: number;
          max_total_source_bytes?: number;
          sensitive_path_rules?: Json;
          configuration_version?: number;
          ai_enabled?: boolean;
          ai_private_metadata_opt_in?: boolean;
          ai_score_threshold?: number;
          is_public_demo?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "repositories_installation_id_fkey";
            columns: ["installation_id"];
            isOneToOne: false;
            referencedRelation: "github_installations";
            referencedColumns: ["id"];
          },
        ];
      };
      source_files: {
        Row: {
          id: string;
          repository_id: string;
          snapshot_id: string;
          path: string;
          language: string;
          file_type: string;
          content_sha: string;
          size_bytes: number;
          is_entry_point: boolean;
          is_test: boolean;
          route_path: string | null;
          parse_status: string;
          parse_error: string | null;
          imports: Json;
          unresolved_imports: Json;
          exported_names: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          repository_id: string;
          snapshot_id: string;
          path: string;
          language?: string;
          file_type?: string;
          content_sha: string;
          size_bytes?: number;
          is_entry_point?: boolean;
          is_test?: boolean;
          route_path?: string | null;
          parse_status?: string;
          parse_error?: string | null;
          imports?: Json;
          unresolved_imports?: Json;
          exported_names?: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          repository_id?: string;
          snapshot_id?: string;
          path?: string;
          language?: string;
          file_type?: string;
          content_sha?: string;
          size_bytes?: number;
          is_entry_point?: boolean;
          is_test?: boolean;
          route_path?: string | null;
          parse_status?: string;
          parse_error?: string | null;
          imports?: Json;
          unresolved_imports?: Json;
          exported_names?: Json;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "source_files_snapshot_id_repository_id_fkey";
            columns: ["snapshot_id","repository_id"];
            isOneToOne: false;
            referencedRelation: "graph_snapshots";
            referencedColumns: ["id","repository_id"];
          },
        ];
      };
      webhook_deliveries: {
        Row: {
          delivery_id: string;
          event_type: string;
          action: string | null;
          event_summary: Json;
          status: string;
          job_id: string | null;
          received_at: string;
          processed_at: string | null;
        };
        Insert: {
          delivery_id: string;
          event_type: string;
          action?: string | null;
          event_summary?: Json;
          status?: string;
          job_id?: string | null;
          received_at?: string;
          processed_at?: string | null;
        };
        Update: {
          delivery_id?: string;
          event_type?: string;
          action?: string | null;
          event_summary?: Json;
          status?: string;
          job_id?: string | null;
          received_at?: string;
          processed_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "webhook_job_fk";
            columns: ["job_id"];
            isOneToOne: false;
            referencedRelation: "jobs";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: { [_ in never]: never };
    Functions: {
      claim_job: {
        Args: {
          p_worker_id: string | null;
          p_job_id?: string | null;
          p_lease_seconds?: number | null;
        };
        Returns: Database["public"]["Tables"]["jobs"]["Row"][];
      };
      finish_job: {
        Args: {
          p_job_id: string | null;
          p_lease_token: string | null;
          p_result: string | null;
          p_error_code?: string | null;
          p_error?: string | null;
          p_retry_at?: string | null;
        };
        Returns: boolean;
      };
      heartbeat_job: {
        Args: {
          p_job_id: string | null;
          p_lease_token: string | null;
          p_lease_seconds?: number | null;
        };
        Returns: boolean;
      };
      record_webhook_and_job: {
        Args: {
          p_delivery_id: string | null;
          p_event_type: string | null;
          p_action: string | null;
          p_event_summary: Json | null;
          p_job?: Json | null;
        };
        Returns: Json;
      };
      retry_job: {
        Args: {
          p_job_id: string | null;
        };
        Returns: boolean;
      };
    };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
};

export const publicTableNames = [
  "ai_explanations",
  "analyses",
  "analysis_changes",
  "analysis_nodes",
  "analysis_score_factors",
  "analysis_test_associations",
  "dependency_edges",
  "faultline_schema_version",
  "github_comments",
  "github_installations",
  "graph_snapshots",
  "impact_paths",
  "jobs",
  "profiles",
  "public_demo_reports",
  "pull_requests",
  "repositories",
  "source_files",
  "webhook_deliveries"
] as const;
